export const caregiverRoles = [
    "Doctor",
    "Nurse",
    "Pharmacist",
    "Administrative Staff",
    "Surgeon",
    "Physician",
    "Dentist",
    "Optometrist",
    "Radiologist",
    "Psychiatrist",
    "Physical Therapist",
    "Occupational Therapist",
    "Medical Lab Technician",
    "Paramedic",
    "Dietitian",
    "Speech Therapist",
    "Medical Assistant",
    "Respiratory Therapist",
    "Midwife",
    "Orthopedist",
    "Cardiologist",
    "Neurologist",
    "Pediatrician",
    "Dermatologist",
    "Gynecologist",
    "Urologist",
    "Oncologist",
    "Endocrinologist",
    "Anesthesiologist",
  ];